travis:
  secure:
    BINSTAR_TOKEN: SdKMVdnOeRqeXJ60nj2TMIgNr+W+jfMmrlCm8EWSTEaTjbuy8Krvb7rtYIy8a7tpD/XZyqnVy91tLCqq7q3NdBCJJztn442BT4x+ozMeniEAxaeD3DWJbAhL1/V/F2PkuCbEGwqOxrFSA2/mQ7RjzeOGvHxOxxI1joMW0XVafZxLJbkXB5vFo10Pu5lfloHEEbrQToMiubGSWmq/pGl9cIqCQ8aK+XEhdN6zX23ekT1kGmGG3raWIe/4K1q6Wm9/O/2wy7P90aTL02QdBB+DPASdESnBdiSgzZn2NCM8Xv42B65B8uhpjTW2AA0829KW1+ykIRbAVlUHmIN6p8atQ3Xd5w43nWn1hu40WH3iZvkkdF581n41eSt7n9QjQmS9upkSFH0xNtiBNMpPd2Dyd+O8UU9w4mvHGX3Pwp2CK4FTgpii2BHsa6U5l1WDNfeh3rF6eifRkel9Okupv3J5EDPAHc1LbjfJzq16WiaOM+r0lNsoha+KT5WwfyETdEIMK8SyClpocPeQAELvhaK12Gm859cXiwj5jfWxqZl8bfShxycHbw0sA2Yu7ept4zihNUb7t+wmmad1DGkKsbYuwhWFD9ylHxRzCuuGZBNLmkXb1KeyV+V6Zz+iZZ0ATCbYxzG33cgcQHOLnc2jdk7kvyzc7Aq+zR0gUnzkJI1fDEM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
